### ISSUE TITLE
Упростить код движения игрока

### ISSUE THREAD

**Issue by igorcoding** [tech-team/no-turning-back#83]

**Comment by alekseyl1992** [comment]
упростил? :D

**Comment by alekseyl1992** [comment]
где ссылка на коммит?)

**Comment by igorcoding** [comment]
![image](https://user-images.githubusercontent.com/5521116/33171759-91851f34-d05e-11e7-9aad-5a7e65691ba4.png)

**Comment by alekseyl1992** [comment]
ясна
просто в почту только строка "Closed #id"
